openapi: 3.0.3
info:
  title: Easyapp API
  version: 1.0.0
  description: API documentation for easyapp
paths:
  /api/hello/:
    get:
      operationId: api_hello_retrieve
      description: Get a hello world message
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
          description: ''
  /api/auth/register/:
    post:
      operationId: api_auth_register_create
      tags:
      - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MemberRegisterRequest'
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Member'
        '400':
          description: Bad Request
  /api/auth/login/:
    post:
      operationId: api_auth_login_create
      tags:
      - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MemberLoginRequest'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Member'
        '400':
          description: Invalid credentials
  /api/auth/me/:
    get:
      operationId: api_auth_me_retrieve
      tags:
      - auth
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Member'
        '401':
          description: Unauthorized
  /api/auth/logout/:
    post:
      operationId: api_auth_logout_create
      tags:
      - auth
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: ''
        '401':
          description: Unauthorized
  /api/chat/messages/:
    get:
      operationId: api_chat_messages_list
      tags:
      - chat
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChatMessage'
        '401':
          description: Unauthorized
    post:
      operationId: api_chat_messages_create
      tags:
      - chat
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatMessageCreateRequest'
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatMessage'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
components:
  schemas:
    Message:
      type: object
      properties:
        message:
          type: string
          maxLength: 200
        timestamp:
          type: string
          format: date-time
          readOnly: true
      required:
      - message
      - timestamp
    Member:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        created_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - id
      - username
      - created_at
    MemberRegisterRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
      - username
      - password
    MemberLoginRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
      - username
      - password
    ChatMessage:
      type: object
      properties:
        id:
          type: integer
        text:
          type: string
        created_at:
          type: string
          format: date-time
        member_id:
          type: integer
        member_username:
          type: string
      required:
      - id
      - text
      - created_at
      - member_id
      - member_username
    ChatMessageCreateRequest:
      type: object
      properties:
        text:
          type: string
      required:
      - text
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
